# Generated by Django 5.1.4 on 2026-07-13 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='接口名称')),
                ('url', models.CharField(max_length=500, verbose_name='请求URL')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='请求参数')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '接口',
                'verbose_name_plural': '接口',
            },
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='测试项名称')),
                ('type', models.IntegerField(choices=[(1, '单接口用例'), (2, '多接口编排'), (3, '自定义脚本')], default=1, verbose_name='项目类型')),
                ('excel_file', models.FileField(blank=True, upload_to='test_cases/', verbose_name='Excel用例文件')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_items', to='api_app.interface', verbose_name='关联接口')),
            ],
            options={
                'verbose_name': '测试项',
                'verbose_name_plural': '测试项',
            },
        ),
    ]
