# Generated by Django 5.1.4 on 2026-07-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interface',
            new_name='DB_Interface',
        ),
        migrations.RenameModel(
            old_name='TestItem',
            new_name='DB_TestItem',
        ),
    ]
