# Generated by Django 5.1.4 on 2026-07-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_rename_interface_db_interface_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_interface',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='db_testitem',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='db_testitem',
            name='interface',
            field=models.IntegerField(default=0, verbose_name='关联接口号'),
        ),
    ]
