# Generated by Django 5.1.4 on 2026-07-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_db_interface_id_alter_db_testitem_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_testitem',
            name='excel_file',
        ),
        migrations.AddField(
            model_name='db_testitem',
            name='cases',
            field=models.JSONField(blank=True, default=list, verbose_name='用例数据'),
        ),
    ]
