# Generated by Django 5.1.4 on 2026-07-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_remove_db_testitem_excel_file_db_testitem_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_testitem',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
