# Generated by Django 5.1.4 on 2026-07-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_alter_db_testitem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_items', models.CharField(max_length=500, verbose_name='测试项ID')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(default='running', max_length=20, verbose_name='状态')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='总用例数')),
                ('passed', models.IntegerField(blank=True, null=True, verbose_name='通过')),
                ('failed', models.IntegerField(blank=True, null=True, verbose_name='失败')),
                ('skipped', models.IntegerField(blank=True, null=True, verbose_name='跳过')),
                ('jenkins_build_url', models.CharField(max_length=500, verbose_name='Jenkins构建链接')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
            ],
        ),
    ]
