# Generated by Django 5.1.4 on 2026-07-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_db_testrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_testitem',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
