# Generated by Django 5.1.4 on 2026-07-22 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_alter_db_run_result_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='db_interface',
            options={'verbose_name': '1_接口表', 'verbose_name_plural': '1_接口表'},
        ),
        migrations.AlterModelOptions(
            name='db_run_result',
            options={'verbose_name': '3_测试记录表', 'verbose_name_plural': '3_测试记录表'},
        ),
        migrations.AlterModelOptions(
            name='db_testitem',
            options={'verbose_name': '2_测试项表', 'verbose_name_plural': '2_测试项表'},
        ),
    ]
