# Generated by Django 5.1.4 on 2026-07-30 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0012_alter_db_run_result_cases_json_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='域名')),
                ('domain', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='域名')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '6_域名表',
                'verbose_name_plural': '6_域名表',
            },
        ),
        migrations.CreateModel(
            name='DB_Env',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='环境标识')),
                ('env', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='环境')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '7_环境表',
                'verbose_name_plural': '7_环境表',
            },
        ),
        migrations.CreateModel(
            name='DB_FirstTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='一级标签名称')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='序号')),
            ],
            options={
                'verbose_name': '4_一级标签',
                'verbose_name_plural': '4_一级标签',
            },
        ),
        migrations.CreateModel(
            name='DB_HeaderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='请求头模板名称')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头内容')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '9_请求头模板表',
                'verbose_name_plural': '9_请求头模板表',
            },
        ),
        migrations.CreateModel(
            name='DB_Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Token名称')),
                ('token', models.TextField(blank=True, null=True, verbose_name='Token值')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '8_Token表',
                'verbose_name_plural': '8_Token表',
            },
        ),
        migrations.AddField(
            model_name='db_testitem',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='db_testitem',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.db_interface', verbose_name='关联接口'),
        ),
        migrations.CreateModel(
            name='DB_SecondTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='二级标签名称')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='序号')),
                ('first_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.db_firsttag', verbose_name='一级标签')),
            ],
            options={
                'verbose_name': '5_二级标签',
                'verbose_name_plural': '5_二级标签',
            },
        ),
    ]
