# Generated by Django 5.1.4 on 2026-07-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0013_db_domain_db_env_db_firsttag_db_headertemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_interface',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='db_interface',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
