# Generated by Django 5.1.4 on 2026-07-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0014_db_interface_sort_alter_db_interface_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_interface',
            name='sort',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='序号'),
        ),
    ]
