# Generated by Django 5.1.4 on 2026-07-31 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0015_alter_db_interface_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_testitem',
            name='second_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.db_secondtag', verbose_name='二级标签'),
        ),
    ]
