# Generated by Django 5.1.4 on 2026-08-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0016_db_testitem_second_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_testitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
