# Generated by Django 5.1.4 on 2026-08-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0017_alter_db_testitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_domain',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='域名名称'),
        ),
        migrations.AlterField(
            model_name='db_env',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='域名名称'),
        ),
    ]
