# Generated by Django 5.1.4 on 2026-08-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0018_alter_db_domain_name_alter_db_env_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_testitem',
            name='script_content',
            field=models.TextField(blank=True, default='', verbose_name='脚本内容'),
        ),
        migrations.AddField(
            model_name='db_testitem',
            name='script_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='脚本文件名'),
        ),
        migrations.AlterField(
            model_name='db_testitem',
            name='type',
            field=models.IntegerField(choices=[(1, '单接口用例'), (2, '自定义脚本')], default=1, verbose_name='项目类型'),
        ),
    ]
