# Generated by Django 5.1.4 on 2026-08-21 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0019_db_testitem_script_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_interface',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.db_firsttag', verbose_name='一级标签'),
        ),
    ]
