# Generated by Django 5.1.4 on 2026-09-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0020_db_interface_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='工具名称')),
                ('tool_key', models.CharField(max_length=50, unique=True, verbose_name='工具标识')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='分类')),
                ('description', models.TextField(blank=True, null=True, verbose_name='工具说明')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='序号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '10_工具表',
                'verbose_name_plural': '10_工具表',
            },
        ),
        migrations.AlterField(
            model_name='db_testitem',
            name='type',
            field=models.IntegerField(choices=[(1, '单接口用例'), (2, '多接口脚本')], default=1, verbose_name='项目类型'),
        ),
    ]
