# Generated by Django 5.1.4 on 2026-09-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0021_db_tool_alter_db_testitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_testitem',
            name='doc_link',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='文档链接'),
        ),
    ]
