# Generated by Django 5.1.4 on 2026-09-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0022_db_testitem_doc_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_SqlEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_name', models.CharField(max_length=50, unique=True, verbose_name='环境名称')),
                ('host', models.CharField(max_length=200, verbose_name='主机')),
                ('port', models.IntegerField(default=3306, verbose_name='端口')),
                ('user', models.CharField(max_length=100, verbose_name='账号')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '11_SQL连接表',
                'verbose_name_plural': '11_SQL连接表',
            },
        ),
        migrations.AddField(
            model_name='db_testitem',
            name='sql_database',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='SQL库名'),
        ),
    ]
