# Generated by Django 5.1.4 on 2026-09-20 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0023_db_sqlenv_db_testitem_sql_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_TestAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='测试用户名')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '12_测试账号表',
                'verbose_name_plural': '12_测试账号表',
            },
        ),
        migrations.DeleteModel(
            name='DB_Token',
        ),
        migrations.AlterModelOptions(
            name='db_domain',
            options={'verbose_name': '06_域名表', 'verbose_name_plural': '06_域名表'},
        ),
        migrations.AlterModelOptions(
            name='db_env',
            options={'verbose_name': '07_环境表', 'verbose_name_plural': '07_环境表'},
        ),
        migrations.AlterModelOptions(
            name='db_firsttag',
            options={'verbose_name': '04_一级标签', 'verbose_name_plural': '04_一级标签'},
        ),
        migrations.AlterModelOptions(
            name='db_headertemplate',
            options={'verbose_name': '09_请求头模板表', 'verbose_name_plural': '09_请求头模板表'},
        ),
        migrations.AlterModelOptions(
            name='db_interface',
            options={'verbose_name': '01_接口表', 'verbose_name_plural': '01_接口表'},
        ),
        migrations.AlterModelOptions(
            name='db_run_result',
            options={'verbose_name': '03_测试记录表', 'verbose_name_plural': '03_测试记录表'},
        ),
        migrations.AlterModelOptions(
            name='db_secondtag',
            options={'verbose_name': '05_二级标签', 'verbose_name_plural': '05_二级标签'},
        ),
        migrations.AlterModelOptions(
            name='db_sqlenv',
            options={'verbose_name': '10_SQL连接表', 'verbose_name_plural': '10_SQL连接表'},
        ),
        migrations.AlterModelOptions(
            name='db_testitem',
            options={'verbose_name': '02_测试项表', 'verbose_name_plural': '02_测试项表'},
        ),
        migrations.AlterModelOptions(
            name='db_tool',
            options={'verbose_name': '11_工具表', 'verbose_name_plural': '11_工具表'},
        ),
        migrations.AddField(
            model_name='db_domain',
            name='app_server',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='App登录域名'),
        ),
        migrations.AddField(
            model_name='db_domain',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='默认项'),
        ),
        migrations.AddField(
            model_name='db_env',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='默认项'),
        ),
        migrations.AddField(
            model_name='db_headertemplate',
            name='system',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='系统类型'),
        ),
        migrations.AddField(
            model_name='db_testitem',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='测试账号'),
        ),
        migrations.AddField(
            model_name='db_testitem',
            name='system',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='测试端'),
        ),
        migrations.AddField(
            model_name='db_testaccount',
            name='env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.db_env', verbose_name='测试环境'),
        ),
        migrations.AlterUniqueTogether(
            name='db_testaccount',
            unique_together={('env', 'username')},
        ),
    ]
