# Generated by Django 5.1.4 on 2026-09-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0026_role_to_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_testitem',
            name='script_inputs',
            field=models.TextField(blank=True, default='', verbose_name='多接口入参'),
        ),
    ]
